import type { Dict, GenerationPayload, Locale } from "./workspace-types";

export const LOCALE_KEY = "video-workflow-locale";
export const LOCALES: Locale[] = ["zh-CN", "en-US"];

export const DEFAULT_GENERATION_PAYLOAD: GenerationPayload = {
  productName: "Miniature Dragon",
  sellingPointsText: "high detail, easy support removal",
  targetAudience: "tabletop gamers",
  tone: "energetic",
  durationSec: 30,
};

export const DEFAULT_VOICE_STYLE = "energetic";

export function localize(locale: Locale, zh: string, en: string): string {
  return locale === "zh-CN" ? zh : en;
}

export const TEXT: Record<Locale, Dict> = {
  "zh-CN": {
    localeLabel: "界面语言",
    modelSettings: "模型配置",
    backToHome: "返回首页",
    textModelProvider: "文本模型供应商",
    imageModelProvider: "图像模型供应商",
    videoModelProvider: "视频模型供应商",
    manualModel: "手动模型",
    modelUnknown: "模型未知",
    providerUnknown: "供应商未知",
    queuedFallback: "排队中",
    languages: { "zh-CN": "中文", "en-US": "English" },
    heroTag: "3D 打印短视频流程",
    heroTitle: "OpenAI + SeaDance 创作控制台",
    heroDesc: "从素材到成片的一站式工作流，统一状态反馈和语言切换。",
    completion: "流程完成度",
    uiLang: "界面语言",
    contentLang: "脚本输出语言",
    projectIdLabel: "项目切换",
    projectIdHint: "项目 ID 由系统自动生成，可在下拉列表里切换已有项目。",
    progressTitle: "执行进度",
    progressHint: "按 1-3 顺序推进，减少返工。",
    quickLang: "快速切换",
    responseTitle: "接口响应",
    responseEmpty: "还没有响应数据。",
    errorPrefix: "请求失败",
    stepTag: "步骤",
    stepNames: {
      materials: "原型图批量生素材",
      script: "生成与编辑脚本",
      video: "提交视频生成",
    },
    stepHints: {
      materials: "先准备可用素材。",
      script: "先生成再编辑。",
      video: "有脚本 ID 后可入队。",
    },
    stepState: {
      done: "已完成",
      blocked: "等待前置",
      active: "进行中",
      pending: "待开始",
    },
    asset: {
      title: "素材上传",
      desc: "可批量上传当前项目源图。",
      fileLabel: "选择素材文件（可多选）",
      submit: "上传素材",
      submitting: "上传中...",
      chooseFile: "请先选择至少一个文件。",
      preview: "素材预览",
    },
    script: {
      title: "脚本生成与编辑",
      desc: "调用 OpenAI 兼容接口生成结构化脚本，再进行编辑。",
      product: "产品名称",
      productPh: "例如：Miniature Dragon",
      points: "卖点（逗号/换行分隔）",
      pointsPh: "高细节, 易去支撑",
      audience: "目标人群",
      audiencePh: "例如：桌游玩家",
      tone: "语气风格",
      tonePh: "例如：energetic",
      duration: "时长（秒）",
      outLang: "脚本输出语言",
      submit: "下一步：生成脚本 + 分镜",
      submitting: "生成中...",
      editTitle: "可编辑字段",
      fieldTitle: "标题",
      hook: "开场钩子",
      sellPoints: "卖点文案",
      storyboard: "分镜",
      cta: "行动号召（CTA）",
      save: "保存脚本编辑",
      saving: "保存中...",
      scriptId: "脚本 ID",
      scriptIdPh: "scr_xxx",
      scriptIdHint: "也可以手动填入已有脚本 ID 继续后续流程。",
      needPoints: "请至少填写一个卖点。",
      needScriptId: "请先生成脚本或输入已有脚本 ID。",
    },
    video: {
      title: "视频任务入队",
      desc: "选择画幅与音色风格后，提交 SeaDance 直出有声视频任务。",
      ratio: "画幅比例",
      voiceStyle: "配音风格",
      voiceStylePh: "例如：energetic",
      vertical: "9:16（竖屏）",
      horizontal: "16:9（横屏）",
      submit: "下一步：提交 SeaDance 任务",
      submitting: "入队中...",
      needScriptId: "缺少脚本 ID，无法生成视频。",
      hint: "需要先在步骤 2 获取有效的脚本 ID。",
      jobId: "任务 ID",
      status: "任务状态",
      polling: "正在查询任务状态...",
      retry: "重试未完成分镜",
      retrying: "重试中...",
      shotStatus: "分镜进度",
      ready: "视频已生成",
    },
    materialGen: {
      title: "原型图批量生成素材",
      desc: "上传原型图，按提示词与参考图批量生成素材图，并自动入库。",
      prompt: "图像提示词",
      promptPh: "例如：咖啡店门头，写实摄影风格，保留品牌元素与暖色调",
      templateName: "模板名称",
      templateNamePh: "例如：门店写实风",
      saveTemplate: "保存为模板",
      savingTemplate: "保存中...",
      chooseTemplate: "选择模板填充",
      prototypeFile: "原型图（单选）",
      refFiles: "参考图（可多选）",
      outputCount: "生成数量",
      size: "尺寸（可选）",
      sizePh: "例如：2048x2048 或 2K",
      submit: "下一步：开始生成素材",
      submitting: "生成中...",
      needPrototype: "请先选择原型图。",
      needPrompt: "请先填写提示词。",
      generated: "素材生成完成。",
    },
  },
  "en-US": {
    localeLabel: "Interface Language",
    modelSettings: "Model Settings",
    backToHome: "Back to Home",
    textModelProvider: "Text Model Provider",
    imageModelProvider: "Image Model Provider",
    videoModelProvider: "Video Model Provider",
    manualModel: "manual model",
    modelUnknown: "model n/a",
    providerUnknown: "provider n/a",
    queuedFallback: "QUEUED",
    languages: { "zh-CN": "中文", "en-US": "English" },
    heroTag: "3D Print Short-Video Workflow",
    heroTitle: "OpenAI + SeaDance Studio Console",
    heroDesc: "Single-screen workflow from assets to final render with stronger stage feedback.",
    completion: "Workflow Completion",
    uiLang: "Interface Language",
    contentLang: "Script Output Language",
    projectIdLabel: "Switch Project",
    projectIdHint: "Project IDs are auto-generated. Use the list to switch between existing projects.",
    progressTitle: "Progress",
    progressHint: "Complete steps 1-3 in order.",
    quickLang: "Quick Switch",
    responseTitle: "API Response",
    responseEmpty: "No response yet.",
    errorPrefix: "Request failed",
    stepTag: "Step",
    stepNames: {
      materials: "Generate Materials",
      script: "Generate & Edit Script",
      video: "Queue Video Render",
    },
    stepHints: {
      materials: "Prepare materials first.",
      script: "Generate first, then edit.",
      video: "Queue once Script ID is available.",
    },
    stepState: {
      done: "Done",
      blocked: "Blocked",
      active: "In Progress",
      pending: "Pending",
    },
    asset: {
      title: "Asset Upload",
      desc: "Upload one or more source images for the current project.",
      fileLabel: "Select asset files (multi-select)",
      submit: "Upload Assets",
      submitting: "Uploading...",
      chooseFile: "Please choose at least one file.",
      preview: "Asset Preview",
    },
    script: {
      title: "Script Generation & Editing",
      desc: "Generate structured script via OpenAI-compatible API, then refine fields.",
      product: "Product Name",
      productPh: "e.g. Miniature Dragon",
      points: "Selling points (comma/newline separated)",
      pointsPh: "high detail, easy support removal",
      audience: "Target Audience",
      audiencePh: "e.g. tabletop gamers",
      tone: "Tone",
      tonePh: "e.g. energetic",
      duration: "Duration (sec)",
      outLang: "Script Output Language",
      submit: "Next: Generate Script + Storyboard",
      submitting: "Generating...",
      editTitle: "Editable Fields",
      fieldTitle: "Title",
      hook: "Hook",
      sellPoints: "Selling Points",
      storyboard: "Storyboard",
      cta: "CTA",
      save: "Save Script Edits",
      saving: "Saving...",
      scriptId: "Script ID",
      scriptIdPh: "scr_xxx",
      scriptIdHint: "You can paste an existing Script ID to continue.",
      needPoints: "Please provide at least one selling point.",
      needScriptId: "Generate a script first or provide an existing Script ID.",
    },
    video: {
      title: "Queue Video Generation",
      desc: "Choose aspect ratio and voice style, then submit a SeaDance audio-video task.",
      ratio: "Aspect Ratio",
      voiceStyle: "Voice Style",
      voiceStylePh: "e.g. energetic",
      vertical: "9:16 (Vertical)",
      horizontal: "16:9 (Horizontal)",
      submit: "Next: Queue SeaDance Video",
      submitting: "Queueing...",
      needScriptId: "scriptId is required to generate video.",
      hint: "A valid Script ID from step 2 is required.",
      jobId: "Render Job ID",
      status: "Render Status",
      polling: "Polling render status...",
      retry: "Retry Unfinished Shots",
      retrying: "Retrying...",
      shotStatus: "Shot Progress",
      ready: "Video is ready",
    },
    materialGen: {
      title: "Generate Materials From Prototype",
      desc: "Upload a prototype image, apply prompt and references, and batch-generate material images.",
      prompt: "Image Prompt",
      promptPh: "e.g. realistic coffee storefront poster, warm cinematic daylight, preserve brand identity",
      templateName: "Template Name",
      templateNamePh: "e.g. Storefront Realistic",
      saveTemplate: "Save As Template",
      savingTemplate: "Saving...",
      chooseTemplate: "Apply Template",
      prototypeFile: "Prototype Image (single)",
      refFiles: "Reference Images (optional)",
      outputCount: "Output Count",
      size: "Size (optional)",
      sizePh: "e.g. 2048x2048 or 2K",
      submit: "Next: Generate Materials",
      submitting: "Generating...",
      needPrototype: "Please choose one prototype image.",
      needPrompt: "Please provide a prompt.",
      generated: "Material generation completed.",
    },
  },
};
